### ISSUE TITLE
Compatibility with Homey Cloud

### ISSUE THREAD

**Issue by chimpinwetsuit** [rkokkelk/com.jreenen.homeyharmonyhub#107]
**Is your feature request related to a problem? Please describe.**
I have joined the Homey (Cloud) Beta and found that this useful app is not compatible (yet).

**Describe the solution you'd like**
Home Cloud compatibility.

**Describe alternatives you've considered**
N/A

**Additional context**
The  information here might be useful:
https://apps.developer.homey.app/guides/homey-cloud

**Comment by rkokkelk** [comment]
This will never be compatible with the Homey Cloud. This is because this system relies on LAN connectivity which the Homey Cloud does not support.
