### ISSUE TITLE
Logitech Harmony hub homey Pro 2023 

### ISSUE THREAD

**Issue by kimc88** [rkokkelk/com.jreenen.homeyharmonyhub#109]
Will the app for the homey Pro support the 2023 model? 
![Screenshot_2022-11-06-22-30-40-57_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/3104661/200196256-b1bedaef-4dea-4833-9ba5-a017596d2a18.jpg)

**Comment by KnarfOfSpam** [comment]
Yes I like the app and use it a lot…

**Comment by satoer** [comment]
Me too, would be great if this can be updated it to SDK3

**Comment by Mintminds** [comment]
Yes please!

**Comment by kranzig** [comment]
Here another request to update the app!

**Comment by Wvanoors** [comment]
If the update comes, I will find me a Harmony hub….. so yes please….

**Comment by bullseye1977** [comment]
That would be great. otherwise i think i wont upgrade tot Homey Pro 2023 (preorder placed)

**Comment by maartenver** [comment]
Hopefully this will be done, I ordered the new Homey Pro 2023 and not having this app would have quite an impact on my routines. It will definitely take some fun away from using the new Homey. In fact, I think I will delay the switch to the new Homey if this is not running on 2023.

**Comment by Wvanoors** [comment]
Hello Roy, could you maybe tell us if you are planning to update the Homey-Harmony app to Hoemy Pro 2023? No is an answer too, even though it would be apity. Or maybe you are thinking aboutit, but not knowing when?

**Comment by Wilocat** [comment]
Here another request to update the app!, Hopefully this will be done, I ordered the new Homey Pro 2023

**Comment by rkokkelk** [comment]
So apparently, I'm not receiving notifications of these messages. But I'm currently spending my free time on updating this app. So hopefully I can release a beta version soon. 

Due to being duplicate, I'm closing this issue and I'm asking to use for further reference the initial issue: #108
