### ISSUE TITLE
Hi! Any chance to get this app ready with SDK3 for Homey Pro 2023? 

### ISSUE THREAD

**Issue by corvdniet** [rkokkelk/com.jreenen.homeyharmonyhub#110]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by johnwoto** [comment]
would love to see the app updated - use it everyday

**Comment by maartenver** [comment]
This is an app I use daily. It would be awesome to get his app working in the new Homey Pro 2023. Hopefully this app will get an update soon. It would be greatly appreciated. 

Will you be able to get this done?

**Comment by rkokkelk** [comment]
I'm currently spending my free time on updating this app. So hopefully I can release a beta version soon.

Due to being duplicate, I'm closing this issue and I'm asking to use for further reference the initial issue: https://github.com/rkokkelk/com.jreenen.homeyharmonyhub/issues/108
