### ISSUE TITLE
Unable to mute several devices

### ISSUE THREAD

**Issue by edwinvdpol** [rkokkelk/com.jreenen.homeyharmonyhub#70]
**Describe the bug**
When I hit the "mute" button in Homey on several devices, it does not work.
It **does** work with my TV (Sony), it does **not** work with my JBL 2.1 soundbar and DVR from KPN.

**To Reproduce**
1. Go to device in Homey
2. Click on 'Gedempt volume (mute)'
3. Notice it does not mute the device

**Expected behavior**
When I click on the 'Mute' button, it should mute the device.

**Desktop (please complete the following information):**
 - Homey firmware version: 4.2.0
 - App version 2.0.3

**Additional context**
The mute button on the remote does work as it should.

**Comment by edwinvdpol** [comment]
@jreenen Yes, it is!

**Comment by jreenen** [comment]
@edwinvdpol while testing if this would work now on the upcoming v2.0.4 version of the homey app I found that the issue is within the Logitech Hub. For the KPN DVR (Arris) device there is no mute function mapped to the device itself and therefore not working on the homey app also.
